# Generated by Django 3.2.7 on 2021-11-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ficcion', 'ficcion'), ('juveniles', 'juveniles'), ('cientificos', 'cientificos')], max_length=20)),
                ('fechapre', models.DateTimeField()),
                ('fechadev', models.DateTimeField()),
            ],
        ),
    ]
